### ISSUE TITLE
Snygg presentation av status och prioritet på uppgifter

### ISSUE THREAD

**Issue by kk222hk** [ev-konsult/ledningssystem#109]
Nu skrivs statusen och prioriteten ut som dom är i tasks/index och tasks/show. Så det står "not_completed", "critical" osv direkt i vyn. Vi behöver nån snygg lösning på det. Kanske ha en liten div-ruta med en viss bakgrundsfärg för olika prioriteter? Ett sånt här tecken ✓ om statusen är klar?

**Comment by mc22dg** [comment]
Klart
