### ISSUE TITLE
Tillbaka knapp på sök anställda

### ISSUE THREAD

**Issue by mj223dg** [ev-konsult/ledningssystem#117]
Finns ingen "avbryt" sökning eller liknande så har man sök på ett namn som inte finns så är det antingen så att man måste söka med ett tomt fält eller gå tillbaka och sedan in på visa anställda igen.

**Comment by kk222hk** [comment]
Gjorde en "Rensa sökning"-knapp som laddar om sidan och därför tar bort sökparametrar. Skrev lite JS också för att visa sökningen så att man vet när man har en aktiv sökning. Sorry om jag snodde din issue men den verkade kul :beers:
