### ISSUE TITLE
Hamburgarmenyn bug

### ISSUE THREAD

**Issue by ad222kr** [ev-konsult/ledningssystem#118]
I mobil-läge så synds bara hamburgarmenyns outline och det blir en hover-effekt på den. När man har tryckt på den en gång så man får upp dash-boarden så försvinner buggen dock.

För att återskapa, ladda sidan. Dra ner till mobilläget och kolla på hamburgarmenyn i högra hörnet.

**Comment by Holmewi** [comment]
Fixat, tills vidare.
