### ISSUE TITLE
information icon

### ISSUE THREAD

**Issue by RebeccaFransson** [ev-konsult/ledningssystem#179]
en rund ring med ett "i" i mitten

**Comment by mc22dg** [comment]
Kan du precisera dig lite mer? :) Har ingen aning om vad du menar.

**Comment by RebeccaFransson** [comment]
Haha jadå, googla på information icon, så finns det bilder!
Den 2 mar 2016 4:36 em skrev "Martin Carlsson" <notifications@github.com>:

**Comment by mc22dg** [comment]
Ok förstår vad det är och såg att ni placerat en vid användar-rättigheterna. Men vart ska övriga placeras?

**Comment by RebeccaFransson** [comment]
Nej alltså, jag skulle vilja att du gör en sån själv. I photoshop eller
illustrator, som har transparant bakgrund. Så slipper vi olagligt ta någon
annans.
Den 2 mar 2016 8:13 em skrev "Martin Carlsson" <notifications@github.com>:

**Comment by mc22dg** [comment]
Jaha ok!

**Comment by Holmewi** [comment]
var inte bootstraps glyphicons bra nog? :) glyphicon glyphicon-info-sign

**Comment by RebeccaFransson** [comment]
Smart! Tänkte vi inte ens på, hehe!
Den 3 mar 2016 9:13 fm skrev "Holmewi" <notifications@github.com>:

**Comment by kk222hk** [comment]
Detta är löst med glyphicons :santa:
