### ISSUE TITLE
Avsändare och ansvarig för task

### ISSUE THREAD

**Issue by Holmewi** [ev-konsult/ledningssystem#213]
Går det fixa att man kan se vem som skapat en uppgift i användarens vy, 
samt visa vem som är ansvarig för uppgiften i admins vy?

**Comment by ad222kr** [comment]
Det här gick väl inte att fixa eftersom vi inte har den kopplingen i databasen @kk222hk ?

**Comment by kk222hk** [comment]
Stämmer..tror vi stänger denna då vi inte bör ändra i databasen så här nära inpå deadline
