### ISSUE TITLE
Översättning av prioritet

### ISSUE THREAD

**Issue by Holmewi** [ev-konsult/ledningssystem#214]
Jag behöver lite hjälp att översätta prioriteterna till Svenska. Jag försökte själv genom att försöka återskapa något liknande i statistics_controller.rb, men fick det inte att funka.

**Comment by kk222hk** [comment]
Nu är det översatt i indexvyn. Angående kolumnen "tilldelad" där det stod Förnamn Efternamn, så tänkte jag på att en uppgift kan ha X antal personer tilldelade. Så jag gjorde en bootstrap popup/modal som man kan klicka upp personal i. Kolla gärna så att det ser ok ut :)
