### ISSUE TITLE
Kristoffer...

### ISSUE THREAD

**Issue by mj223dg** [ev-konsult/ledningssystem#223]
Datetime saken fungerade inte. Har du tid att kolla på den och höra av dig till mig, samtidigt så att jag får vara delaktig och veta hur vi löser det.

**Comment by kk222hk** [comment]
Yes ska kika på det senare i eftermiddag så skriver jag här sen!

**Comment by kk222hk** [comment]
Nu kom jag hem och hann kolla lite på det. 

Jag får inte det från stackoverflow att funka heller. Tror att det beror på att vi har döpt ett av fältet till "end", vilket är ett keyword för att avsluta en metod i ruby.

Vi kan lösa det med ett regex, då blir det såhär i task.rb:

Regex som matchar YYYY-MM-DD (standardformatet för DateTime)
`VALID_DATE_REGEX = /(\d{4})-(\d{2})-(\d{2})/i`

För att använda det på fälten:

`validates :start,             format: { with: VALID_DATE_REGEX },
                                presence: true`

 `validates :end,               format: { with: VALID_DATE_REGEX },
                                presence: true` 

I vyn kommer det att se ut som förut, med en datepicker, när man använder Chrome. I Firefox får man fortfarande skriva in i ett textfält, men man får valideringsfel istället för att det kraschar om man gör fel. Man kan lägga till en placeholder på fälten i vyn så att man ser vilket format det ska vara, till exempel:

`<%= f.date_field :end, class: "form-control", placeholder: "YYYY-MM-DD" %>`

Känns det som en ok lösning?
