### ISSUE TITLE
404 och 500-sida

### ISSUE THREAD

**Issue by kk222hk** [ev-konsult/ledningssystem#273]
I mappen "public" finns statiska felsidor som visas på heroku (lokalt visas stack tracen istället).

400.html visas när man skriver fel URL, tex https://intraev.herokuapp.com/users/9999999

500.html är den generella felsidan om något kraschar.

Kanske styla till dessa lite? Skriva på svenska och göra dom mer lila..

**Comment by Holmewi** [comment]
ah, ska kolla på det :)

**Comment by kk222hk** [comment]
Verkar som att martin har jobbat lite med detta, du kan ju höra med honom om ni vill så ni inte får konflikter

**Comment by mc22dg** [comment]
Har gjort två enkla men funktionella.
