### ISSUE TITLE
Martin! Styla en p-tag

### ISSUE THREAD

**Issue by RebeccaFransson** [ev-konsult/ledningssystem#304]
p-taggen ligger på rad 40 i views/tasks/_user_task_list.
Denna skall vara snyggare och ligga åt höger, som knapparna på de andra tasksen:)
Denna p-tag visas när en uppgift är avslutad

**Comment by mc22dg** [comment]
Fixat men kan inte commita av någon anledning...
Får be Alex och Kristoffer om hjälp med det img
