### ISSUE TITLE
Färdigställa all testdokumentation innan leverans till kund

### ISSUE THREAD

**Issue by RebeccaFransson** [ev-konsult/ledningssystem#329]
Beskriv vad integrationstester är i [testdokumentationen](https://github.com/ev-konsult/ledningssystem/wiki/Testdokumentation-och-testrutin).
Skapa tester för 1.5, 1.9, 4.5, 5.1

**Comment by kk222hk** [comment]
Dokumentationen stämmer överens med testerna nu, lade till en förklaring av integrationstester.
  
1.9 och 5.1 hade ett par tester redan (dom var inte dokumenterade bara). Gjorde ett controllertest för statistiken, och ett ett [manuellt test för CSRF-kravet](https://github.com/ev-konsult/ledningssystem/wiki/Manuellatester#csrf-test).
