### ISSUE TITLE
FRONT-END: Behövs javascript för admin-dashboard

### ISSUE THREAD

**Issue by ad222kr** [ev-konsult/ledningssystem#40]
app/views/users/show.html.erb

När admin loggar in och kollar på en enskild användares profil ska han kunna lägga till utbildning och kontaktperson. Dessa formulär bör gömmas via css och sedan plockas fram med hjälp av javascript när admin trycker på t.ex "Lägg till utbildning".

Formuläret för utbildning finns redan.

Fråga om det är otydligt!

**Comment by kk222hk** [comment]
Fixat för utbildning nu. Kontaktperson är kvar.

**Comment by kk222hk** [comment]
Kontaktpersonen läggs till när man skapar användare nu, så jag stänger detta då det är klart för utbildningsformuläret
