### ISSUE TITLE
Ajax bug...

### ISSUE THREAD

**Issue by mj223dg** [ev-konsult/ledningssystem#63]
Validering i ajax-formuläret failar...
@kk222hk

**Comment by kk222hk** [comment]
Nu fungerar valideringen även med ajax. Man får dock ett generiskt felmeddelande om att det inte gick att spara utbildningen, istället för att varje separat felmeddelande skrivs ut..ska se om det går att lösa. Stänger denna så länge

**Comment by kk222hk** [comment]
Nu fungerar det helt (varje felmeddelande skrivs ut). yay!
