### ISSUE TITLE
Översättning

### ISSUE THREAD

**Issue by ad222kr** [ev-konsult/ledningssystem#85]
Översättning av validerings-fel.
Helt inte i en.yml utan sv-SE.yml

**Comment by Grenmyr** [comment]
https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/sv.yml

**Comment by ad222kr** [comment]
Tack, snällt!

**Comment by ad222kr** [comment]
Översättningar finns nu i sv.yml. Dock så står det fortfarande "Description får inte vara blank". Dvs att attributens namn översätts inte. Måste lösas

**Comment by kk222hk** [comment]
Jag fick det att fungera, så att attributen översätts. Men då får jag translation missing på status-dropdownen..verkar vara något problem med indentering som fuckar upp .yml filen.

**Comment by ad222kr** [comment]
Okej. Ta en titt på det imorgon i skolan?

**Comment by kk222hk** [comment]
Yep jag ger upp för idag :)

**Comment by kk222hk** [comment]
Nu funkar det !
